### ISSUE TITLE
python: can't open file '/github/workspace/./main.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by alvarolorentedev** [TrisNol/trello-create-card-action#1]
Hello @TrisNol thanks a lot for creating this action. I have tried to use it but got the next error.
```sh
python: can't open file '/github/workspace/./main.py': [Errno 2] No such file or directory
```

You can find more logs in this [run log](https://github.com/kanekotic/openai-to-trello-social/actions/runs/5226091395/jobs/9436373733).

Thanks in advance for any help you can provide.

**Comment by TrisNol** [comment]
Hi @kanekotic, thanks for raising the issue and the detailed description. The bug should be fixed now, please test it again.

**Comment by alvarolorentedev** [comment]
awesome...this one is solved :)

**Comment by alvarolorentedev** [comment]
I am now facing a deserialization issue from line 24, will check if I can fork and fix it
